project:
  type: website
  resources:
    - img/soil-dataset.png
    - img/soil-report.png
    - maps/*
  render:
    - "*.md"
    - "*.qmd"

website:
  favicon: /assets/images/favicon.svg
  repo-url: "https://github.com/kalro-ict/kensis"
  repo-actions:
    - edit
    - issue
  page-footer:
    left:
    - text: Kenya Soil Survey

  title: "Soil Data of Kenya"
  search: false
  navbar:
    pinned: true
    logo: ./img/kenya-soil-survey.png
    logo-alt: "Logo of Kenya Soil Survey"
    right:
      - text: Home
        file: "./index.qmd"
      - text: Data
        file: "data/index.qmd"
      - text: Map Viewer
        file: "./index.qmd"
      - text: Dashboard
        file: "./index.qmd"
      - text: Publications
        file: "reports/index.qmd"
      - text: Documentation
        file: "./docs.md"  
      - text: About
        file: "./about.md"

format:
  html:
    page-layout: full
    theme:
      light: flatly
      dark: darkly
    
